version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  db:
    driver: local
  cache:
    driver: local

